<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="8.0.11" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="OrchardCore.Abstractions" Version="3.0.0" />
    <PackageReference Include="OrchardCore.Autoroute" Version="3.0.0" />
    <PackageReference Include="OrchardCore.Module.Targets" Version="3.0.0" />
    <PackageReference Include="OrchardCore.ContentManagement" Version="3.0.0" />
    <PackageReference Include="OrchardCore.ContentTypes.Abstractions" Version="3.0.0" />
    <PackageReference Include="OrchardCore.DisplayManagement" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
    <Folder Include="Workflows\" />
  </ItemGroup>

</Project>
