<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migrations\**" />
    <EmbeddedResource Remove="Migrations\**" />
    <None Remove="Migrations\**" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="OrchardCore.Abstractions" Version="3.0.1" />
    <PackageReference Include="OrchardCore.Autoroute" Version="3.0.1" />
    <PackageReference Include="OrchardCore.Module.Targets" Version="3.0.1" />
    <PackageReference Include="OrchardCore.ContentManagement" Version="3.0.1" />
    <PackageReference Include="OrchardCore.ContentTypes.Abstractions" Version="3.0.1" />
    <PackageReference Include="OrchardCore.DisplayManagement" Version="3.0.1" />
    <PackageReference Include="OrchardCore.Workflows.Abstractions" Version="3.0.1" />
  </ItemGroup>

</Project>
